name: pipeline-2

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: yarn --frozen-lockfile
      - run: yarn test

  test-local:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run deployment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: yarn --frozen-lockfile
      - run: yarn test
